# -*- coding: utf-8 -*-
"""Spectrogram Fix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AfUYKr5TJE3rL-Iqqr54Ds7QlZlc3_55

# **Spectogram untuk Musik**
"""

import os
import librosa
import librosa.display
import IPython.display as ipd
import numpy as np
import matplotlib.pyplot as plt

! pip install pydub

from pydub import AudioSegment
from IPython.display import Audio
import soundfile as sf

! pip install pysoundfile

"""# 1. Musik Classic

## Lagu Prelude No. 2 (Classic) BPM: 53
"""

audio_file1 = 'Prelude No. 2.wav'

ipd.Audio(audio_file1)

x, sr = librosa.load(audio_file1)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas

fig = plt.Figure()
canvas = FigureCanvas(fig)
ax = fig.add_subplot(111)
fig.savefig('Classic1.png')

data, rate = sf.read(audio_file1)
data

"""## Lagu Sérénade à Notre Dame de Paris (Classic) BPM: 60"""

audio_file2 = 'Sérénade à Notre Dame de Paris.wav'

ipd.Audio(audio_file2)

x, sr = librosa.load(audio_file2)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

data, rate = sf.read(audio_file2)
data

"""## Lagu Ethos by Johannes Bornlof (Classic) BPM: 50"""

audio_file3 = 'ES_Ethos - Johannes Bornlof.wav'

ipd.Audio(audio_file3)

data, rate = sf.read(audio_file3)
data

x, sr = librosa.load(audio_file3)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Prelude No. 13 (Classic) BPM: 56"""

audio_file4 = 'Prelude No. 13.wav'

ipd.Audio(audio_file4)

data, rate = sf.read(audio_file4)
data

x, sr = librosa.load(audio_file4)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Prelude No. 18 (Classic) BPM: 56"""

audio_file5 = 'Prelude No. 18.wav'

ipd.Audio(audio_file5)

data, rate = sf.read(audio_file5)
data

x, sr = librosa.load(audio_file5)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Beneath The Stars (Classic) BPM: 60"""

audio_file6 = 'beneath-the-stars-7481.wav'

ipd.Audio(audio_file6)

data, rate = sf.read(audio_file6)
data

x, sr = librosa.load(audio_file6)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Wistful Rain by Ghostrifter Official (Classic) BPM: 99

"""

audio_fileC7 = 'Wistful Rain by Ghostrifter Official.wav'

ipd.Audio(audio_fileC7)

data, rate = sf.read(audio_fileC7)
data

x, sr = librosa.load(audio_fileC7)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu This Too Shall Pass by Scott Buckley (Classic) BPM: 89"""

audio_fileC8 = 'This Too Shall Pass Scott Buckley.wav'

ipd.Audio(audio_fileC8)

data, rate = sf.read(audio_fileC8)
data

x, sr = librosa.load(audio_fileC8)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Midsommar by Scott Buckley (Classic) BPM: 106"""

audio_fileC9 = 'Midsommar - Scott Buckley.wav'

ipd.Audio(audio_fileC9)

data, rate = sf.read(audio_fileC9)
data

x, sr = librosa.load(audio_fileC9)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Reverie by Lahar (Classic) BPM: 144"""

audio_fileC10 = 'Reverie (Piano Version) - Lahar.wav'

ipd.Audio(audio_fileC10)

data, rate = sf.read(audio_fileC10)
data

x, sr = librosa.load(audio_fileC10)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""# Lagu Life In Silico by Scott Buckley BPM: 89"""

audio_fileC11 = 'Life In Silico – Scott Buckley.wav'

data, rate = sf.read(audio_fileC11)
data

x, sr = librosa.load(audio_fileC11)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""# Lagu Undertow by Scott Buckley BPM: 108"""

audio_fileC12 = 'Undertow by Scott Buckley.wav'

data, rate = sf.read(audio_fileC12)
data

x, sr = librosa.load(audio_fileC12)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""# Lagu Supreme by JayJen Music BPM: 135"""

audio_fileC13 = 'JayJen - Supreme.wav'

data, rate = sf.read(audio_fileC13)
data

x, sr = librosa.load(audio_fileC13)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""# Lagu I Walk With Ghosts by Scott Buckley BPM: 112"""

audio_fileC14 = 'I Walk With Ghosts – Scott Buckley.wav'

data, rate = sf.read(audio_fileC14)
data

x, sr = librosa.load(audio_fileC14)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""# Lagu Lights by Alex-Productions BPM: 89"""

audio_fileC15 = 'Lights – Alex Productions.wav'

data, rate = sf.read(audio_fileC15)
data

x, sr = librosa.load(audio_fileC15)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""# 2. Musik Pop

## Lagu How I Know by Dylan Emmet (Pop) BPM: 82
"""

audio_fileP1 = 'How I Know – Dylan Emmet.wav'

ipd.Audio(audio_fileP1)

def get_wav_info(audio_fileP1):
    data, rate = sf.read(audio_fileP1)
    return data, rate

data, rate = sf.read(audio_fileP1)
data

x, sr = librosa.load(audio_fileP1)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu I Need It by Jay Someday (Pop) BPM: 85 """

audio_fileP2 = 'I Need It – Jay Someday.wav'

ipd.Audio(audio_fileP2)

def get_wav_info(audio_fileP2):
    data, rate = sf.read(audio_fileP2)
    return data, rate

data, rate = sf.read(audio_fileP2)
data

x, sr = librosa.load(audio_fileP2)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Memories Erased by RYYZN (Pop) BPM: 74"""

audio_fileP3 = 'Memories Erased (Instrumental) – RYYZN.wav'

ipd.Audio(audio_fileP3)

def get_wav_info(audio_fileP3):
    data, rate = sf.read(audio_fileP3)
    return data, rate

data, rate = sf.read(audio_fileP3)
data

x, sr = librosa.load(audio_fileP3)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Descriptions by RYYZN (Pop) BPM: 97"""

audio_fileP4 = 'Descriptions – RYYZN.wav'

ipd.Audio(audio_fileP4)

def get_wav_info(audio_fileP4):
    data, rate = sf.read(audio_fileP4)
    return data, rate

data, rate = sf.read(audio_fileP4)
data

x, sr = librosa.load(audio_fileP4)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Don't Wanna Think About It by Dylan Emmet (Pop) BPM: 86"""

audio_fileP5 = 'Dont Wanna Think About It – Dylan Emmet.wav'

ipd.Audio(audio_fileP5)

def get_wav_info(audio_fileP5):
    data, rate = sf.read(audio_fileP5)
    return data, rate

data, rate = sf.read(audio_fileP5)
data

x, sr = librosa.load(audio_fileP5)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Stars by Vlad Gluschenko (Pop) BPM: 63"""

audio_fileP6 = 'Stars by Vlad Gluschenko.wav'

ipd.Audio(audio_fileP6)

def get_wav_info(audio_fileP6):
    data, rate = sf.read(audio_fileP6)
    return data, rate

data, rate = sf.read(audio_fileP6)
data

x, sr = librosa.load(audio_fileP6)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu 4 You by Jay Someday (Pop) BPM: 116"""

audio_fileP7 = '4 You – Jay Someday.wav'

ipd.Audio(audio_fileP7)

def get_wav_info(audio_fileP7):
    data, rate = sf.read(audio_fileP7)
    return data, rate

data, rate = sf.read(audio_fileP7)
data

x, sr = librosa.load(audio_fileP7)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Flood by RYYZN (Pop) BPM: 160"""

audio_fileP8 = 'Flood (Instrumental) – RYYZN.wav'

ipd.Audio(audio_fileP8)

def get_wav_info(audio_fileP8):
    data, rate = sf.read(audio_fileP8)
    return data, rate

data, rate = sf.read(audio_fileP8)
data

x, sr = librosa.load(audio_fileP8)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Fresh Up by tubebackr (Pop) BPM: 107"""

audio_fileP9 = 'Fresh Up – tubebackr.wav'

ipd.Audio(audio_fileP9)

def get_wav_info(audio_fileP9):
    data, rate = sf.read(audio_fileP9)
    return data, rate

data, rate = sf.read(audio_fileP9)
data

x, sr = librosa.load(audio_fileP9)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu New Beginnings by Beau Walker (Pop) BPM: 111"""

audio_fileP10 = 'New Beginnings – Beau Walker.wav'

ipd.Audio(audio_fileP10)

def get_wav_info(audio_fileP10):
    data, rate = sf.read(audio_fileP10)
    return data, rate

data, rate = sf.read(audio_fileP10)
data

x, sr = librosa.load(audio_fileP10)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""# Lagu Lost by Alex-Productions BPM: 117 """

audio_fileP11 = 'Lost – Alex-Productions.wav'

data, rate = sf.read(audio_fileP11)
data

x, sr = librosa.load(audio_fileP11)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""# Lagu Flowers - Sakura Girl BPM: 104"""

audio_fileP12 = 'Flowers – Sakura Girl.wav'

data, rate = sf.read(audio_fileP12)
data

x, sr = librosa.load(audio_fileP12)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""# Lagu Puff by Limujii BPM: 118"""

audio_fileP13 = 'Puff – Limujii.wav'

data, rate = sf.read(audio_fileP13)
data

x, sr = librosa.load(audio_fileP13)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""# Lagu Flipside by Dylan Emmet BPM: 135"""

audio_fileP14 = 'Flipside – Dylan Emmet.wav'

data, rate = sf.read(audio_fileP14)
data

x, sr = librosa.load(audio_fileP14)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""# Lagu Blue Sweater (Instrumental) by RYYZN BPM: 116


"""

audio_fileP15 = 'Blue Sweater - Instrumental – RYYZN.wav'

data, rate = sf.read(audio_fileP15)
data

x, sr = librosa.load(audio_fileP15)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""# 3. Musik Jazz

## Lagu I Knew a Guy (Jazz) BPM: 75
"""

audio_fileJ1 = 'I Knew a Guy.wav'

ipd.Audio(audio_fileJ1)

def get_wav_info(audio_fileJ1):
    data, rate = sf.read(audio_fileJ1)
    return data, rate

data, rate = sf.read(audio_fileJ1)
data

x, sr = librosa.load(audio_fileJ1)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Midnight Stroll (Jazz) BPM: 83"""

audio_fileJ2 = 'Midnight Stroll [Relaxing Study Music].wav'

ipd.Audio(audio_fileJ2)

def get_wav_info(audio_fileJ2):
    data, rate = sf.read(audio_file1J2
    return data, rate

data, rate = sf.read(audio_fileJ2)
data

x, sr = librosa.load(audio_fileJ2)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Remember by HaTom (Jazz) BPM: 86"""

audio_fileJ3 = 'Remember – HaTom (instrumental).wav'

ipd.Audio(audio_fileJ3)

def get_wav_info(audio_fileJ3):
    data, rate = sf.read(audio_fileJ3)
    return data, rate

data, rate = sf.read(audio_fileJ3)
data

x, sr = librosa.load(audio_fileJ3)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Sun Shines Through the Leaves by Babasmas (Jazz) BPM: 89"""

audio_fileJ4 = 'sun shines through the leaves – Babasmas.wav'

ipd.Audio(audio_fileJ4)

def get_wav_info(audio_fileJ4):
    data, rate = sf.read(audio_fileJ4)
    return data, rate

data, rate = sf.read(audio_fileJ4)
data

x, sr = librosa.load(audio_fileJ4)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Grove Grove (Jazz) BPM: 92"""

audio_fileJ5 = 'Groove Grove.wav'

ipd.Audio(audio_fileJ5)

def get_wav_info(audio_fileJ5):
    data, rate = sf.read(audio_fileJ5)
    return data, rate

data, rate = sf.read(audio_fileJ5)
data

x, sr = librosa.load(audio_fileJ5)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Afraid of Expressing Myself by Babasmas (Jazz) BPM: 89"""

audio_fileJ6 = 'afraid of expressing myself – Babasmas.wav'

ipd.Audio(audio_fileJ6)

def get_wav_info(audio_fileJ6):
    data, rate = sf.read(audio_fileJ6)
    return data, rate

data, rate = sf.read(audio_fileJ6)
data

x, sr = librosa.load(audio_fileJ6)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Jazzy by Sakura Hz (Jazz) BPM: 128"""

audio_fileJ7 = 'Jazzy – sakura Hz.wav'

ipd.Audio(audio_fileJ7)

def get_wav_info(audio_fileJ7):
    data, rate = sf.read(audio_fileJ7)
    return data, rate

data, rate = sf.read(audio_fileJ7)
data

x, sr = librosa.load(audio_fileJ7)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Lovely Swindler by Amarià (Jazz) BPM: 99"""

audio_fileJ8 = 'Lovely Swindler by Amarià.wav'

ipd.Audio(audio_fileJ8)

def get_wav_info(audio_fileJ8):
    data, rate = sf.read(audio_fileJ8)
    return data, rate

data, rate = sf.read(audio_fileJ8)
data

x, sr = librosa.load(audio_fileJ8)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Quiet Night by Tokyo Music Walker (Jazz) BPM: 153"""

audio_fileJ9 = 'Quiet Night – Tokyo Music Walker.wav'

ipd.Audio(audio_fileJ9)

def get_wav_info(audio_fileJ9):
    data, rate = sf.read(audio_fileJ9)
    return data, rate

data, rate = sf.read(audio_fileJ9)
data

x, sr = librosa.load(audio_fileJ9)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Twenty by Peyruis (Jazz) BPM: 99"""

audio_fileJ10 = 'Twenties - Peyruis.wav'

ipd.Audio(audio_fileJ10)

def get_wav_info(audio_fileJ10):
    data, rate = sf.read(audio_fileJ10)
    return data, rate

data, rate = sf.read(audio_fileJ10)
data

x, sr = librosa.load(audio_fileJ10)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""# 4. Musik Soul

## Lagu Day in Paris by Pyrosion (Soul) BPM: 74
"""

audio_fileS1 = 'Day In Paris – Pyrosion.wav'

ipd.Audio(audio_fileS1)

def get_wav_info(audio_fileS1):
    data, rate = sf.read(audio_fileS1)
    return data, rate

date, rate = sf.read(audio_fileS1)
data

x, sr = librosa.load(audio_fileS1)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Coffee Break by Pyrosion (Soul) BPM: 75"""

audio_fileS2 = 'Coffee Break – Pyrosion.wav'

ipd.Audio(audio_fileS2)

def get_wav_info(audio_fileS2):
    data, rate = sf.read(audio_fileS2)
    return data, rate

data, rate = sf.read(audio_fileS2)
data

x, sr = librosa.load(audio_fileS2)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Dreamer (Soul) BPM: 75"""

audio_fileS3 = 'Dreamer.wav'

ipd.Audio(audio_fileS3)

def get_wav_info(audio_fileS3):
    data, rate = sf.read(audio_fileS3)
    return data, rate

data, rate = sf.read(audio_fileS3)
data

x, sr = librosa.load(audio_fileS3)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Token by Fernweh (Soul) BPM: 65"""

audio_fileS4 = 'fernweh - Token (Feat. Cloe Sutherland).wav'

ipd.Audio(audio_fileS4)

def get_wav_info(audio_fileS4):
    data, rate = sf.read(audio_fileS4)
    return data, rate

data, rate = sf.read(audio_fileS4)
data

x, sr = librosa.load(audio_fileS4)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Faithfull Mission by Artificial.Music (Soul) BPM: 74"""

audio_fileS5 = 'Faithful Mission – Artificial.Music.wav'

ipd.Audio(audio_fileS5)

def get_wav_info(audio_fileS5):
    data, rate = sf.read(audio_fileS5)
    return data, rate

data, rate = sf.read(audio_fileS5)
data

x, sr = librosa.load(audio_fileS5)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Asleep by HaTom (Soul) BPM: 80"""

audio_fileS6 = 'Asleep - HaTom.wav'

ipd.Audio(audio_fileS6)

def get_wav_info(audio_fileS6):
    data, rate = sf.read(audio_fileS6)
    return data, rate

data, rate = sf.read(audio_fileS6)
data

x, sr = librosa.load(audio_fileS6)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Bad Intentions by Le Gang (Soul) BPM: 103"""

audio_fileS7 = 'Bad Intentions – Le Gang.wav'

ipd.Audio(audio_fileS7)

def get_wav_info(audio_fileS7):
    data, rate = sf.read(audio_fileS7)
    return data, rate

data, rate = sf.read(audio_fileS7)
data

x, sr = librosa.load(audio_fileS7)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Distância by Pyrosion (Soul) BPM: 89"""

audio_fileS8 = 'Distância – Pyrosion.wav'

ipd.Audio(audio_fileS8)

def get_wav_info(audio_fileS8):
    data, rate = sf.read(audio_fileS8)
    return data, rate

data, rate = sf.read(audio_fileS8)
data

x, sr = librosa.load(audio_fileS8)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Frames by Pyrosion (Soul) BPM: 107"""

audio_fileS9 = 'Frames - Pyrosion.wav'

ipd.Audio(audio_fileS9)

def get_wav_info(audio_fileS9):
    data, rate = sf.read(audio_fileS9)
    return data, rate

data, rate = sf.read(audio_fileS9)
data

x, sr = librosa.load(audio_fileS9)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Rolex by RYYZN (Soul) BPM: 121"""

audio_fileS10 = 'Rolex (Instrumental) by RYYZN.wav'

ipd.Audio(audio_fileS10)

def get_wav_info(audio_fileS10):
    data, rate = sf.read(audio_fileS10)
    return data, rate

data, rate = sf.read(audio_fileS10)
data

x, sr = librosa.load(audio_fileS10)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""# Lagu Cinderella (Instrumental) by RYYZN BPM: 128"""

audio_fileS11 = 'Cinderella (Instrumental) – RYYZN.wav'

data, rate = sf.read(audio_fileS11)
data

x, sr = librosa.load(audio_fileS11)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""# Lagu Winding Road by Pyrosion BPM: 93"""

audio_fileS12 = 'Winding Road by Pyrosion.wav'

data, rate = sf.read(audio_fileS12)
data

x, sr = librosa.load(audio_fileS12)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""# Failles (Instrumental) by HaTom BPM: 92"""

audio_fileS13 = 'Failles (Instrumental) by HaTom.wav'

data, rate = sf.read(audio_fileS13)
data

x, sr = librosa.load(audio_fileS13)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""# Road Trip by Pyrosion BPM: 103"""

audio_fileS14 = 'Road Trip.wav'

data, rate = sf.read(audio_fileS14)
data

x, sr = librosa.load(audio_fileS14)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""# Lagu Up Above by Pyrosion BPM: 95"""

audio_fileS15 = 'Up Above.wav'

data, rate = sf.read(audio_fileS15)
data

x, sr = librosa.load(audio_fileS15)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""# 5. Musik Folk

## Lagu Anita Latina by Le Gang (Folk) BPM: 92
"""

audio_fileF1 = 'anita-latina.wav'

ipd.Audio(audio_fileF1)

def get_wav_info(audio_fileF1):
    data, rate = sf.read(audio_fileF1)
    return data, rate

data, rate = sf.read(audio_fileF1)
data

x, sr = librosa.load(audio_fileF1)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Serenity by Jason Shaw (Folk) BPM: 81"""

audio_fileF2 = 'Jason Shaw - SERENITY.wav'

ipd.Audio(audio_fileF2)

def get_wav_info(audio_fileF2):
    data, rate = sf.read(audio_file2F2)
    return data, rate

data, rate = sf.read(audio_fileF2)
data

x, sr = librosa.load(audio_fileF2)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Solo Acoustic Guitar by Jason Shaw (Folk) BPM: 99"""

audio_fileF3 = 'Jason Shaw - SOLO ACOUSTIC GUITAR.wav'

ipd.Audio(audio_fileF3)

def get_wav_info(audio_fileF3):
    data, rate = sf.read(audio_fileF3)
    return data, rate

data, rate = sf.read(audio_fileF3)
data

x, sr = librosa.load(audio_fileF3)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Running Waters by Jason Shaw (Folk) BPM: 81"""

audio_fileF4 = 'RunningWaters.wav'

ipd.Audio(audio_fileF4)

def get_wav_info(audio_fileF4):
    data, rate = sf.read(audio_fileF4)
    return data, rate

data, rate = sf.read(audio_fileF4)
data

x, sr = librosa.load(audio_fileF4)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Purpose by Jonny Easton (Folk) BPM: 66"""

audio_fileF5 = 'Purpose - Jonny Easton.wav'

ipd.Audio(audio_fileF5)

def get_wav_info(audio_fileF5):
    data, rate = sf.read(audio_fileF5)
    return data, rate

data, rate = sf.read(audio_fileF5)
data

x, sr = librosa.load(audio_fileF5)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Flowers of The Forest (Folk) BPM: 89"""

audio_fileF6 = 'flowers-of-the-forest-11063.wav'

ipd.Audio(audio_fileF6)

def get_wav_info(audio_fileF6):
    data, rate = sf.read(audio_fileF6)
    return data, rate

data, rate = sf.read(audio_fileF6)
data

x, sr = librosa.load(audio_fileF6)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Forest by Vlad Gluschenko (Folk) BPM: 128"""

audio_fileF7 = 'Forest - Vlad Gluschenko.wav'

ipd.Audio(audio_fileF7)

def get_wav_info(audio_fileF7):
    data, rate = sf.read(audio_fileF7)
    return data, rate

data, rate = sf.read(audio_fileF7)
data

x, sr = librosa.load(audio_fileF7)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Everything Will Be Okay by Beau Walker (Folk) BPM:117 """

audio_fileF8 = 'Everything Will Be Okay – Beau Walker.wav'

ipd.Audio(audio_fileF8)

def get_wav_info(audio_fileF8):
    data, rate = sf.read(audio_fileF8)
    return data, rate

data, rate = sf.read(audio_fileF8)
data

x, sr = librosa.load(audio_fileF8)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Acoustic/Folk Instrumental by Hyde (Folk) BPM: 112"""

audio_fileF9 = 'Acoustic - Folk Instrumental by Hyde.wav'

ipd.Audio(audio_fileF9)

def get_wav_info(audio_fileF9):
    data, rate = sf.read(audio_fileF9)
    return data, rate

data, rate = sf.read(audio_fileF9)
data

x, sr = librosa.load(audio_fileF9)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""## Lagu Wanderlust by Scott Buckley (Folk) BPM: 129"""

audio_fileF10 = 'Wanderlust - Scott Buckley.wav'

ipd.Audio(audio_fileF10)

def get_wav_info(audio_fileF10):
    data, rate = sf.read(audio_file10)
    return data, rate

data, rate = sf.read(audio_fileF10)
data

x, sr = librosa.load(audio_fileF10)
X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize = (10, 5))
librosa.display.specshow(Xdb, sr = sr, x_axis = 'time', y_axis = 'hz')
plt.colorbar()

"""#CRNN

"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import librosa.display
import pylab
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import librosa    
import glob
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from keras import optimizers
import keras

from keras import backend as K
from keras.layers import Input, Dense
from keras.models import Model
from keras.layers import Dense, Dropout, Reshape, Permute
from keras.layers.convolutional import Convolution2D
from keras.layers.convolutional import MaxPooling2D, ZeroPadding2D
from keras.layers.advanced_activations import ELU
from keras.layers.recurrent import GRU

# %matplotlib inline

audio_data = []
labels = []
sampling_rate = []
file_names = []

data, samplerate = librosa.load("Prelude No. 2.wav")
print(data.shape)
print(samplerate)

df_all[('set', 'split')].unique()

classes = ["Classic", "Pop", "Jazz", "Soul", "Folk"]
label_number=0
audio_data = []
labels = []
sampling_rate = []
file_names = []
data = []
noisy_removed=[]
noise=[]
for filepath in glob.iglob('dataset/*'):
    
    #print(filepath[9:])
    
    #print(filepath)
    classes.append(filepath[8:])
print(classes)

for i in classes:
    print("the class = "+i+", the label = "+str(label_number))
    for j in glob.iglob('dataset/'+i+'/*'):
        #samplerate, data = wavfile.read(j)
        y, s = librosa.load(j, sr=44000) # Downsample 44.1kHz to 8kHz
        #reduced_noise = nr.reduce_noise(audio_clip=y, noise_clip=y, verbose=False)
        #print(s)
        #print(j)
        data.append([y,label_number])
        #noise.append(y)
        #labels.append(label_number)
        
    label_number = label_number + 1
print(len(labels))
#print(labels)

model = Sequential()

model.add(Conv2D(16, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
#'''
#model.add(Dropout(0.2))

model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

#model.add(Dropout(0.2))

#'''
#'''
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
#'''


model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors

#model.add(Dense(1000))#input_shape=features.shape[1:]
model.add(Dense(64))#input_shape=features.shape[1:]

model.add(Dense(10))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])